"""Add original_filename to raw_data

Revision ID: 3375db3f15dc
Revises: 43eacc7c9206
Create Date: 2025-09-10 12:19:59.249166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3375db3f15dc'
down_revision = '43eacc7c9206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_data', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
